
services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER?User not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Password not set}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - database:/home/yatd-db
    ports:
      - "5432:5432"

  api:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      REDIS_URL: ${REDIS_URL} 
      WEB_CONCURRENCY: 2
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  database:
